model:
  model_path: '../Model/Nyx/'
  result_path: '../Result/Nyx/'
  vq:
     learning_rate: 5e-5
     epochs: 400
     params:
      in_ch: 1
      out_ch: 1
      hidden_dims: [32,64,128]
  anr:
    learning_rate: 0.0005
    epochs: 400
    params:
      spatial_dim: 3
      ensemble_dim: 4
      out_dim: 1
      embed_dim: 256
      n_embed: 32
      head_dim: 128
      n_head: 4
      hidden_dim: 512
      use_pe: True
      pe_dim: 10
      pe_sigma: 1024
      att_threshold: 0.0015
      mode: 'mlp'

data:
  dataset: 'Nyx'
  factor: 1
  anr_factor: 1
  num_ensemble_training: 200
  time_steps: 100
  batch_size: 65536
  res: [128,128,128]
  scale: [4,4,4]
  crop_size: [128,128,128]
  path: '/root/autodl-tmp/Data/Nyx/'
